### ISSUE TITLE
Fix error with Assessment Plan - Quiz/Test

### ISSUE THREAD

**Issue by KolbeML** [Cyber4All/bloomin-onion-client#17]
After selecting Quiz/Test from the Assessment Plan dropdown list during learning object creation, attempting to select Essay will re-assign the first dropdown choice to Essay, and attempting to select any other option from the second dropdown list will re-assign the first dropdown choice to null/empty. All choices will result in the disappearance of the second dropdown list.

**Comment by tylernhoward** [comment]
The logic for combining these is twofold. On one hand, the need for two separate objects for one single case where quiz test seems to be overkill. Likewise, accommodating and storing another variable for this selection will cause reconfiguring of the database interaction layer/ schema etc. 

Thus, I have placed the test-quiz-strategies in their appropriate assessment-strategies.

Going to close this.
