### ISSUE TITLE
No required elements for learning objects?

### ISSUE THREAD

**Issue by KolbeML** [Cyber4All/bloomin-onion-client#23]
At present, none of the elements of learning objects (Name, Learning Goals, Learning Outcomes, Assessment Plans, Instructional Strategies) are currently required when creating a new object. This means users can create and save a completely empty object. Is this intentional? If not, which elements do we want to require?

**Comment by tylernhoward** [comment]
@nrwinner will be handling validation of these forms using ngForms in the new revamped UI.

**Comment by KolbeML** [comment]
Resolved in commit b074be217c0cde6eb4091f5451c131edbe5f9c75
