### ISSUE TITLE
Revamp Onion UI

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/bloomin-onion-client#26]
Completely refresh the UI of Onion

**Comment by nrwinner** [comment]
![no learning objects](https://user-images.githubusercontent.com/7431390/34627959-ab0a7d8e-f230-11e7-97d9-1536f757dc99.png)
![with learning objects](https://user-images.githubusercontent.com/7431390/34627960-ab15124e-f230-11e7-94be-dd37688205d8.png)

**Comment by Jewel7** [comment]
# Login Example
Notes: Attempting to place the register button on the upper right hand corner and later on, maybe a picture/icon to associate with onion like so ...
![example1loginpage](https://user-images.githubusercontent.com/25856532/34876313-fba17386-f76e-11e7-92c5-68e5ad0001f9.jpg)

**Comment by Jewel7** [comment]
# Forgot Password link example

![forgotpasswordexample1](https://user-images.githubusercontent.com/25856532/34876390-47fcf57a-f76f-11e7-8f7a-81c32744c77a.jpg)

**Comment by tylernhoward** [comment]
Will close with issue #9
