### ISSUE TITLE
Separate taxon selection from outcome verb selection with information on Bloom's taxonomy

### ISSUE THREAD

**Issue by ksherb1** [Cyber4All/bloomin-onion-client#4]
Change the user workflow so that the user selects the Bloom taxon (Remember/Understand etc.) before the outcome verb (Define, Identify, etc.).

The current setup, with the two on the same line, was done so that users can see the verbs associated with each taxon, and essentially pick the taxon based on the verb they're after. This picking of the taxon based on what the outcome should achieve is the behavior we want, but we would like to ensure the users appreciate the significance of the cognitive level. Thus, giving the taxon selection its own space which we can use to provide explanations or whatnot.

See https://teachonline.asu.edu/objectives-builder/ for a low-tech, non-cs model of what we're after.

**Comment by Jewel7** [comment]
We may potentially consider removing the hamburger icon (three horizontal bars) next to the "suggest"  button.

**Comment by Jewel7** [comment]
![img_4921](https://user-images.githubusercontent.com/25856532/33778514-0106274a-dc17-11e7-85ac-05bf27cd1fae.JPG)

**Comment by tylernhoward** [comment]
Work was done here on visually separating the taxonomy from the outcome verb. More work needs to take place in regards to styling and the "more info/help" function.
