### ISSUE TITLE
What is this dialog box? See image. 

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/bloomin-onion-client#43]
<img width="390" alt="screen shot 2018-02-01 at 4 20 46 pm" src="https://user-images.githubusercontent.com/2423261/35704015-09ee3b06-076c-11e8-9bbe-d18bd731be4c.png">

this is popping up randomly when onion client is open.

**Comment by DonSeannelly** [comment]
This seems to be happening when the request times out. Possibly attempting to display the full error object instead of a descriptive message.

If anyone else on @Cyber4All/developers can reproduce this, please comment.
