### ISSUE TITLE
Add metadata with text boxes to learning object 

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/bloomin-onion-client#44]
need: 
Level: Graduate/Undergraduate/K-12

**Comment by gshaw1997** [comment]
Level property added to clark-entity see https://github.com/Cyber4All/clark-entity/commit/90b8a27b8b08112948fc14ebb3a5583ba9521b4c.

@nrwinner  An additional select input, that fits it current workflow, is needed for the user to set appropriate level.
