### ISSUE TITLE
Spell check not working

### ISSUE THREAD

**Issue by EVogel1999** [Cyber4All/bloomin-onion-client#49]
Spell check is not working in the assessment plans text box field.

**Comment by gshaw1997** [comment]
@tylernhoward Is spell check an available feature of the text editor?

**Comment by tylernhoward** [comment]
It is an available feature, I will consult the team regarding the text-editor staying around for beta release

**Comment by DonSeannelly** [comment]
@tylernhoward the text editor for assessment plans/instructional strategies will not be in the beta. We'll be pulling it out with our deployment tomorrow
