### ISSUE TITLE
Multiple target academic levels for learning objects

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/bloomin-onion-client#59]
Each learning object could be targeted at multiple levels - graduate, undergraduate, k-12. Allow multiple selections when creating and editing.

**Comment by DonSeannelly** [comment]
@tylernhoward @gshaw1997 is the API capable of storing multiple? If it is we can update the client, otherwise can a feature request be opened in the correct repo and tagged here?

**Comment by siddharthkaza** [comment]
Any progress on this? Again seems to be a usability issue.

**Comment by gshaw1997** [comment]
Closed in https://github.com/Cyber4All/clark-client/commit/038c5cc6e51208ca633470888629188c310611c1
