### ISSUE TITLE
Feature request - Standard Outcomes listing should be sorted by author

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/bloomin-onion-client#60]

**Comment by DonSeannelly** [comment]
Can you provide more detail to this request? The standard outcomes listed within the suggestion component are grouped by author in the default state. There is also the option to filter by a specific author.

**Comment by siddharthkaza** [comment]
<img width="1170" alt="screen shot 2018-02-17 at 12 28 58 pm" src="https://user-images.githubusercontent.com/2423261/36343770-52fd0ed4-13de-11e8-9bfc-7c8352192803.png">
The filter by Author works great. But it doesn't appear that it is grouped by author. See screenshot.
