### ISSUE TITLE
Revamp Registration Form

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/bloomin-onion-client#7]
## The registration form should do the following:

- Display an error to the user when the provided email is already in use with an active account
- Block form submission when the provided email is not a valid email pattern
- Display an error to the user when the provided username is already in use with an active account

**Comment by DonSeannelly** [comment]
The NCCP Workshop will only feature a demo by a single user. Registration updates are no longer a priority.

**Comment by gshaw1997** [comment]
Currently, there is no way to search for an active user by their email, so no way to check if an email is associated with an active account.

**Comment by KolbeML** [comment]
Resolved by commit "Fix email verification" (messed up my commit message :P )
