### ISSUE TITLE
LO suggestion is only triggered by a "space" being hit in text box

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/bloomin-onion-client#70]
So if you copy and paste a piece of text, and hit suggest, no suggestions. But if you put a space in the text at end now, it works. 
Solution: hitting "suggest" should also trigger a hit to LO suggestion service.

**Comment by gshaw1997** [comment]
@nrwinner Would it be possible to copy over the LO suggestion implementation from CUBE to Onion. That would resolve this issue.

**Comment by siddharthkaza** [comment]
Guys this doesn't have to be fixed now. Only non breaking changes tonight please :)

**Comment by DonSeannelly** [comment]
The next patch release should replace the old hacky watch-for-spacebar with the debounceTime method. Not a priority right now.

**Comment by siddharthkaza** [comment]
Ok. This is definitely a high priority issue. Lowers the usability significantly.

**Comment by gshaw1997** [comment]
Closed in https://github.com/Cyber4All/bloomin-onion-client/commit/784e88cbac05c947bf91a701ca09b9b6a2ad253b
