### ISSUE TITLE
Upload materials screen should have a way out

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/bloomin-onion-client#71]
<img width="1238" alt="screen shot 2018-02-19 at 8 49 42 pm" src="https://user-images.githubusercontent.com/2423261/36404073-c07df8ea-15b6-11e8-9936-0ab80ec4cfc5.png">

See figure. I have uploaded several files. Now I want to leave screen. Only way to do it is use breadcrumbs on top. I think there should be either a button to go back on bottom or breadcrumbs below too.

**Comment by gshaw1997** [comment]
@siddharthkaza Currently, uploading only occurs when the save button is hit which is also one mechanism to navigate away from the page. The cancel button and the breadcrumb at the top both navigate away from the upload materials screen and takes the user back to the dashboard.

Are you suggesting that the cancel button be relabeled to clearly show the navigation relation?

**Comment by DonSeannelly** [comment]
@gshaw1997 maybe we can label it as "Quit to Dashboard" or we could add a mouse-over popup that provides additional text, such as "Cancel this upload and go back to my dashboard" ?

**Comment by siddharthkaza** [comment]
Actually it’s less about cancellation. Might be better explained in person.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DonSeannelly** [comment]
1. Add a confirmation dialog to cancel button
2. Change "Save" to "Upload & Save"
