### ISSUE TITLE
Display Mapped Standards Outside of the Suggestion Component

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/bloomin-onion-client#9]
The LearningObjectBuilder should provide a means to map standard outcomes to learning outcomes that the user is entering. This can be done via the following request.

#### The suggestions component should do the following:
- Emit a standard when the checkbox is selected so that it can be bound to the user's outcome
- Emit an event to unbind the standard to the user's outcome when the checkbox is deselected

#### The learning outcome list item in the LearningObjectBuilder should be converted into it's own component. This component should:
- maintain the existing functionality
- provide a listing of all standard outcomes that the learning outcome is mapped to, even when the suggestion component is closed
- provide a means of unmapping the standard outcome from the learning outcome

**Comment by tylernhoward** [comment]
Suggestions component and mappings component need to be married and styled appropriately.
